<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    require $vh;
?>
<main>
    <div class="container">
        <div class="jumbotron">
            <h1>Hello, Welcome to My Classified!</h1>
            <p class="lead">Loren ipsum dolor sit amet, consectetur adupiscing elit. Vivamus non nisi imperdiet portitor ut a sem. Nullam non porta magna. Phasellus varius ligula cursus tellus ullamcorper.</p>
            <a class="btn btn-primary" href="<?php echo URL;?>items" role="button">View my Items</a>
        </div>
    </div>
</main>
