<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    $pgn = $vw . 'shared/pagination_partial.phtml';
    require $vh;
    $pg = $this->pagination;
    $mo = $this->model;
    $page_number = intVal($pg['page_number']);
    $page_count = intVal($pg['page_count']);
    $total_item = intVal($pg['total_item']);
    $start = (($page_number - 1) * 3) +1;
    $end = ($page_number * 3) > $total_item ? $total_item : ($page_number * 3);
    $list_link = "categories";
    $param = [];
?>
<main>
    <div class="container">
        <?php if(count($mo)>0):?>
            <div class="row">
                <div class="col-md-12">
                    <h4 class="custom-content-title">Categories</h4>
                    <div class="card-deck">
                        <?php for($x =($start-1); $x < $end; $x++): ?>
                            <div class="card custom-card">
                                <div class="card-body">
                                    <a href="<?php echo URL . "item?category=" . $mo[$x]["id"];?>">
                                        <h5 class="card-title"><?php echo $mo[$x]["title"];?></h5>
                                    </a>
                                    <p class="card-text"><?php echo $mo[$x]["description"];?></p>
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>
        <?php else:?>
            <div class="row">
                <div class="col-md-12">
                    <h5>No categories are listed</h5>
                </div>
            </div>
        <?php endif;?>
        <?php if(count($mo)>0):?>
            <div class="row mt-3">
                <div class="col-md-12 text-right">
                    <?php require $pgn;?>
                </div>
            </div>
        <?php endif;?>
    </div>
</main>

