<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    require $vh;
?>

<main>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center mt-5">
                <h1 class="custom-error-header">404</h1>
                <p class="mb-0">Oops Page not found</p>
                <small>Sorry but the page you are looking for is not found.</small>
            </div>
        </div>
    </div>
</main>
