<?php
    global $vw;
    $vh = $vw . 'shared/admin_header.phtml';
    require $vh;
?>
<main>
    <div class="container">
        <h4 class="custom-content-title"><?php echo $this->title ?></h4>
        <hr>
        <form class="form-account" method="post" action="<?php echo URL;?>account/savesubmit">
            <input type="hidden" name="id" value="<?php echo $this->model['id'] ?>">
            <input type="hidden" name="task" value="<?php echo $this->task ?>">
            <div class="form-group row">
                <label for="accountFirstName" class="text-right col-sm-2 col-form-label">First Name</label>
                <div class="col-sm-10">
                    <input type="text" required class="form-control" id="accountFirstName" name="firstname" placeholder="First Name*" value="<?php echo $this->model['first_name'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="accountLastName" class="text-right col-sm-2 col-form-label">Last Name</label>
                <div class="col-sm-10">
                    <input type="text" required class="form-control" id="accountLastName" name="lastname" placeholder="Last Name*" value="<?php echo $this->model['last_name'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="accountEmail" class="text-right col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" required class="form-control" id="accountEmail" name="email" placeholder="Email*" value="<?php echo $this->model['email'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="accountUserName" class="text-right col-sm-2 col-form-label"> User Name</label>
                <div class="col-sm-10">
                    <input type="text" required class="form-control" id="accountUserName" name="username" placeholder="Username*" value="<?php echo $this->model['username'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="accountPassword" class="text-right col-sm-2 col-form-label"> Password</label>
                <div class="col-sm-10">
                    <input type="password" required class="form-control" id="accountPassword" name="password" placeholder="Password*" value="<?php echo $this->model['password'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="accountConfirmPassword" class="text-right col-sm-2 col-form-label">Confirm Password</label>
                <div class="col-sm-10">
                    <input type="password" required class="form-control" id="accountConfirmPassword" name="confirmpassword" placeholder="Confirm Password*" value="">
                </div>
            </div>
            <div class="form-group row hide form-alert-msg">
                <div class="col-sm-10 offset-sm-2">
                    <div class="alert alert-danger alert-full" role="alert">

                    </div>
                </div>
            </div>
            <div class="form-group row row">
                <div class="col-sm-10 offset-md-2 ">
                    <a href="#" class="btn btn-sm btn-primary mr-2 btn-account-submit"> Save Changes</button>
                    <a class="btn btn-sm btn-secondary" href="<?php echo URL;?>account"> Cancel</a>
                </div>
            </div>
        </form>
    </div>
</main>