<main>
    <div class="container">
        <div class="row custom-form-tm">
            <div class="col-md-6 offset-md-3">
                <div class="text-left">
                    <h3>Advance Web Development</h1>
                    <small>COMP1230 Assignment 2 Version 1.0</small>
                    <!--<small><?php #echo $this->model ?></small>-->
                </div>
                <div class="card">
                    <div class="card-body">
                        <form class="form-signin" method="post" action="<?php echo URL;?>account/loginsubmit">
                            <div class="form-group">
                                <label for="InputUsername">USERNAME</label>
                                <div class="custom-input">
                                    <span class="fa fa-user"></span>
                                    <input name="username" type="text" class="form-control" id="InputUsername" aria-describedby="usernameHelp">
                                </div>
                                <small id="usernameHelp" class="form-text text-muted">Your username must be unique.</small>
                            </div>
                            <div class="form-group">
                                <label for="InputPassword">PASSWORD</label>
                                <div class="custom-input">
                                    <span class="fa fa-lock"></span>
                                    <input name="password" type="password" class="form-control" id="InputPassword">
                                </div>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary btn-block btn-lg"><span class="fa fa-sign-in"></span> Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>