<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    require $vh;
    $mo = $this->model;
    $dm = $this->db_manager;
    $category = $this->category;
    $data = $dm->getTrack($mo["id"]);
?>
<main>
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-8 offset-md-2">
                <h3 class="custom-content-title">Information</h3>
                <div class="card custom-card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <div class="custom-img-container mt-3 mb-3">
                                <img src="<?php echo URL . $mo["image"];?>" class="card-img" alt="<?php echo $mo["title"];?>">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h2 class="card-title"><?php echo $mo["title"];?></h2>
                                <p class="card-text"><?php echo $mo["description"];?></p>
                                <span class="badge badge-pill badge-primary"><?php echo $category["title"]?></span>
                                <div class="text-right">
                                    <h4><?php echo "$". $mo["price"];?></h4>
                                    <a class="btn btn-primary" href="<?php echo URL . 'items'?>">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</main>