<?php
    global $vw;
    $vh = $vw . 'shared/visitor_header.phtml';
    $pgn = $vw . 'shared/pagination_partial.phtml';
    $cpv = $vw . 'shared/category_partial.phtml';
    require $vh;
    $pg = $this->pagination;
    $categories = $this->categories;
    $mo = $this->model;
    $dm =  $this->db_manager;
    $page_number = intVal($pg['page_number']);
    $page_count = intVal($pg['page_count']);
    $total_item = intVal($pg['total_item']);
    $start = (($page_number - 1) * 3) +1;
    $end = ($page_number * 3) > $total_item ? $total_item : ($page_number * 3);
    $list_link = "search";
    $param = [];
    if(isset($_GET['keyword'])){
        $param["keyword"] =$_GET['keyword'] ;
    }
?>
<main>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <?php require $cpv;?>
            </div>
            <div class="col-md-8">
                <div class="row mt-3 mb-3">
                    <div class="col-md-8 offset-md-2">
                        <form class="form-inline">
                            <div class="input-group mb-2 mr-sm-2 custom-search">
                                <span class="fa fa-search"></span>
                                <input type="text" class="form-control" id="inlineFormInputGroupSearch" placeholder="keyword..." name="keyword" value="<?php echo $this->keyword;?>">
                                <div class="input-group-append">
                                    <button type submit class="btn btn-outline-primary" type="button">Go</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <?php if(count($this->model)>0 && !empty($this->keyword)):?>
                    <div class="card-deck custom-card">
                        <?php for($x =($start-1); $x < $end; $x++): ?>
                            <div class="card custom-card">
                                <div class="text-center mt-2 mb-2 custom-img-container">
                                    <img src="<?php echo URL . $mo[$x]["image"]?>" class="card-img-top img-responsive" alt="<?php echo $mo[$x]["title"]?>">
                                </div>
                                <div class="card-body">
                                    <a href="<?php echo URL . 'item/info/' . $mo[$x]["id"];?>">
                                        <h5 class="card-title"><?php echo $mo[$x]["title"]?></h5>
                                    </a>
                                    <p class="card-text"><?php echo $mo[$x]["description"]?></p>
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                <?php elseif(!empty($this->keyword)):?>
                    <div class="text-left">
                        <div class="alert alert-danger" role="alert">
                            <small>Cannot find the items, change the keyword and try again.</small>
                        </div>
                    </div>
                <?php endif;?>
                <?php if(count($mo)>0):?>
                    <div class="text-right mt-3">
                        <?php require $pgn;?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</main>